---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: yarn
    image: node:17-alpine
    commands:
      - yarn

  - name: yarn lint
    image: node:17-alpine
    commands:
      - yarn lint

  # - name: npm
  #   image: plugins/npm
  #   settings:
  #     username:
  #       from_secret: npm_username
  #     password:
  #       from_secret: npm_password
  #     email: tyhou13@gmx.com
  #     registry: https://registry.npmjs.org/:_authToken=$NPM_TOKEN
  #     token:
  #       from_secret: npm_token
  #   environment:
  #     NPM_TOKEN:
  #       from_secret: npm_token
  #   when:
  #     ref:
  #       - refs/tags/*
  - name: npm publish
    image: node:17-alpine
    commands:

      - npm config set //registry.npmjs.org/:_authToken "NPM_TOKEN""
      - echo "registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - npm publish
    environment:
      NPM_TOKEN:
        from_secret: npm_token

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:

  - name: yarn
    image: node:17-alpine
    commands:
      - yarn

  - name: yarn lint
    image: node:17-alpine
    commands:
      - yarn lint
